'use client'

export interface SlotSymbol {
  id: string
  name: string
  emoji: string
  label?: string // 特殊符号的英文标签
  rarity: 'A' | 'B' | 'C' | 'D' | 'E' | 'F' | 'G' | 'H' | 'I' | 'WILD' | 'SCATTER' | 'BONUS'
  type: 'normal' | 'wild' | 'scatter' | 'bonus'
}

export interface SlotMachineTheme {
  id: string
  number: number
  name: string
  background: string
  primaryColor: string
  secondaryColor: string
  accentColor: string
  symbols: SlotSymbol[]
}

export const SLOT_MACHINE_THEMES: SlotMachineTheme[] = [
  // 机台01：龍騰怒火
  {
    id: 'slot-01',
    number: 1,
    name: '龍騰怒火',
    background: 'linear-gradient(135deg, #8b0000 0%, #ff4500 100%)',
    primaryColor: '#ff4500',
    secondaryColor: '#8b0000',
    accentColor: '#ffd700',
    symbols: [
      { id: 's1', name: '龍', emoji: '🐉', rarity: 'A', type: 'normal' },
      { id: 's2', name: '火焰', emoji: '🔥', rarity: 'B', type: 'normal' },
      { id: 's3', name: '金塔', emoji: '🏯', rarity: 'C', type: 'normal' },
      { id: 's4', name: '寶劍', emoji: '⚔️', rarity: 'D', type: 'normal' },
      { id: 's5', name: '龍珠', emoji: '🔮', rarity: 'E', type: 'normal' },
      { id: 's6', name: '戰鼓', emoji: '🥁', rarity: 'F', type: 'normal' },
      { id: 's7', name: '幸運符', emoji: '🧧', rarity: 'G', type: 'normal' },
      { id: 's8', name: '紅蓮', emoji: '🌺', rarity: 'H', type: 'normal' },
      { id: 's9', name: '烈火', emoji: '💥', rarity: 'I', type: 'normal' },
      { id: 'wild', name: 'WILD', emoji: '⭐', label: 'WILD', rarity: 'WILD', type: 'wild' },
      { id: 'scatter', name: 'SCATTER', emoji: '✨', label: 'SCATTER', rarity: 'SCATTER', type: 'scatter' },
      { id: 'bonus', name: 'BONUS', emoji: '🎊', label: 'BONUS', rarity: 'BONUS', type: 'bonus' },
    ],
  },
  // 机台02：鳳凰烈焰
  {
    id: 'slot-02',
    number: 2,
    name: '鳳凰烈焰',
    background: 'linear-gradient(135deg, #ff6b00 0%, #ffa500 100%)',
    primaryColor: '#ffa500',
    secondaryColor: '#ff6b00',
    accentColor: '#ffed4e',
    symbols: [
      { id: 's1', name: '鳳凰', emoji: '🦅', rarity: 'A', type: 'normal' },
      { id: 's2', name: '太陽', emoji: '☀️', rarity: 'B', type: 'normal' },
      { id: 's3', name: '羽毛', emoji: '🪶', rarity: 'C', type: 'normal' },
      { id: 's4', name: '火球', emoji: '🔆', rarity: 'D', type: 'normal' },
      { id: 's5', name: '王冠', emoji: '👑', rarity: 'E', type: 'normal' },
      { id: 's6', name: '金環', emoji: '💍', rarity: 'F', type: 'normal' },
      { id: 's7', name: '烈焰星', emoji: '⛅', rarity: 'G', type: 'normal' },
      { id: 's8', name: '金心', emoji: '💛', rarity: 'H', type: 'normal' },
      { id: 's9', name: '鳳鳴', emoji: '🎶', rarity: 'I', type: 'normal' },
      { id: 'wild', name: 'WILD', emoji: '🌟', label: 'WILD', rarity: 'WILD', type: 'wild' },
      { id: 'scatter', name: 'SCATTER', emoji: '🌠', label: 'SCATTER', rarity: 'SCATTER', type: 'scatter' },
      { id: 'bonus', name: 'BONUS', emoji: '🏆', label: 'BONUS', rarity: 'BONUS', type: 'bonus' },
    ],
  },
  // 机台03：海洋深淵
  {
    id: 'slot-03',
    number: 3,
    name: '海洋深淵',
    background: 'linear-gradient(135deg, #001f3f 0%, #0074d9 100%)',
    primaryColor: '#0074d9',
    secondaryColor: '#001f3f',
    accentColor: '#7fdbca',
    symbols: [
      { id: 's1', name: '鯊魚', emoji: '🦈', rarity: 'A', type: 'normal' },
      { id: 's2', name: '海浪', emoji: '🌊', rarity: 'B', type: 'normal' },
      { id: 's3', name: '海星', emoji: '🌟', rarity: 'C', type: 'normal' },
      { id: 's4', name: '珍珠', emoji: '🦪', rarity: 'D', type: 'normal' },
      { id: 's5', name: '三叉戟', emoji: '🔱', rarity: 'E', type: 'normal' },
      { id: 's6', name: '貝殼', emoji: '🐚', rarity: 'F', type: 'normal' },
      { id: 's7', name: '海草', emoji: '🌿', rarity: 'G', type: 'normal' },
      { id: 's8', name: '藍心', emoji: '💙', rarity: 'H', type: 'normal' },
      { id: 's9', name: '漩渦', emoji: '🌀', rarity: 'I', type: 'normal' },
      { id: 'wild', name: 'WILD', emoji: '💎', label: 'WILD', rarity: 'WILD', type: 'wild' },
      { id: 'scatter', name: 'SCATTER', emoji: '🫧', label: 'SCATTER', rarity: 'SCATTER', type: 'scatter' },
      { id: 'bonus', name: 'BONUS', emoji: '⚓', label: 'BONUS', rarity: 'BONUS', type: 'bonus' },
    ],
  },
  // 机台04：精靈森林
  {
    id: 'slot-04',
    number: 4,
    name: '精靈森林',
    background: 'linear-gradient(135deg, #1b5e20 0%, #4caf50 100%)',
    primaryColor: '#4caf50',
    secondaryColor: '#1b5e20',
    accentColor: '#81c784',
    symbols: [
      { id: 's1', name: '精靈', emoji: '🧚', rarity: 'A', type: 'normal' },
      { id: 's2', name: '樹葉', emoji: '🍃', rarity: 'B', type: 'normal' },
      { id: 's3', name: '蘑菇', emoji: '🍄', rarity: 'C', type: 'normal' },
      { id: 's4', name: '櫻花', emoji: '🌸', rarity: 'D', type: 'normal' },
      { id: 's5', name: '聖杯', emoji: '🏆', rarity: 'E', type: 'normal' },
      { id: 's6', name: '竹子', emoji: '🎋', rarity: 'F', type: 'normal' },
      { id: 's7', name: '螢火', emoji: '🟢', rarity: 'G', type: 'normal' },
      { id: 's8', name: '綠心', emoji: '💚', rarity: 'H', type: 'normal' },
      { id: 's9', name: '樹根', emoji: '🌳', rarity: 'I', type: 'normal' },
      { id: 'wild', name: 'WILD', emoji: '🍀', label: 'WILD', rarity: 'WILD', type: 'wild' },
      { id: 'scatter', name: 'SCATTER', emoji: '🌱', label: 'SCATTER', rarity: 'SCATTER', type: 'scatter' },
      { id: 'bonus', name: 'BONUS', emoji: '🎁', label: 'BONUS', rarity: 'BONUS', type: 'bonus' },
    ],
  },
  // 机台05：星際宇宙
  {
    id: 'slot-05',
    number: 5,
    name: '星際宇宙',
    background: 'linear-gradient(135deg, #0a0e27 0%, #3d5a9b 100%)',
    primaryColor: '#3d5a9b',
    secondaryColor: '#0a0e27',
    accentColor: '#64b5f6',
    symbols: [
      { id: 's1', name: '火箭', emoji: '🚀', rarity: 'A', type: 'normal' },
      { id: 's2', name: '星星', emoji: '⭐', rarity: 'B', type: 'normal' },
      { id: 's3', name: '月球', emoji: '🌙', rarity: 'C', type: 'normal' },
      { id: 's4', name: '彗星', emoji: '☄️', rarity: 'D', type: 'normal' },
      { id: 's5', name: '飛碟', emoji: '🛸', rarity: 'E', type: 'normal' },
      { id: 's6', name: '衛星', emoji: '🛰️', rarity: 'F', type: 'normal' },
      { id: 's7', name: '星雲', emoji: '🌌', rarity: 'G', type: 'normal' },
      { id: 's8', name: '紫心', emoji: '💜', rarity: 'H', type: 'normal' },
      { id: 's9', name: '銀河', emoji: '🌃', rarity: 'I', type: 'normal' },
      { id: 'wild', name: 'WILD', emoji: '💫', label: 'WILD', rarity: 'WILD', type: 'wild' },
      { id: 'scatter', name: 'SCATTER', emoji: '🌠', label: 'SCATTER', rarity: 'SCATTER', type: 'scatter' },
      { id: 'bonus', name: 'BONUS', emoji: '🎯', label: 'BONUS', rarity: 'BONUS', type: 'bonus' },
    ],
  },
  // 机台06：沙漠之王
  {
    id: 'slot-06',
    number: 6,
    name: '沙漠之王',
    background: 'linear-gradient(135deg, #8b6914 0%, #daa520 100%)',
    primaryColor: '#daa520',
    secondaryColor: '#8b6914',
    accentColor: '#ffd700',
    symbols: [
      { id: 's1', name: '獅子', emoji: '🦁', rarity: 'A', type: 'normal' },
      { id: 's2', name: '沙漠', emoji: '🏜️', rarity: 'B', type: 'normal' },
      { id: 's3', name: '駱駝', emoji: '🐫', rarity: 'C', type: 'normal' },
      { id: 's4', name: '金字塔', emoji: '🏛️', rarity: 'D', type: 'normal' },
      { id: 's5', name: '聖甲蟲', emoji: '🪲', rarity: 'E', type: 'normal' },
      { id: 's6', name: '沙漏', emoji: '⏳', rarity: 'F', type: 'normal' },
      { id: 's7', name: '棕櫚樹', emoji: '🌴', rarity: 'G', type: 'normal' },
      { id: 's8', name: '黃心', emoji: '💛', rarity: 'H', type: 'normal' },
      { id: 's9', name: '風暴', emoji: '🌪️', rarity: 'I', type: 'normal' },
      { id: 'wild', name: 'WILD', emoji: '👑', label: 'WILD', rarity: 'WILD', type: 'wild' },
      { id: 'scatter', name: 'SCATTER', emoji: '💎', label: 'SCATTER', rarity: 'SCATTER', type: 'scatter' },
      { id: 'bonus', name: 'BONUS', emoji: '🎪', label: 'BONUS', rarity: 'BONUS', type: 'bonus' },
    ],
  },
  // 机台07：冰雪皇後
  {
    id: 'slot-07',
    number: 7,
    name: '冰雪皇後',
    background: 'linear-gradient(135deg, #00bfff 0%, #4169e1 100%)',
    primaryColor: '#00bfff',
    secondaryColor: '#1e90ff',
    accentColor: '#ffffff',
    symbols: [
      { id: 's1', name: '皇後', emoji: '👸', rarity: 'A', type: 'normal' },
      { id: 's2', name: '冰晶', emoji: '❄️', rarity: 'B', type: 'normal' },
      { id: 's3', name: '雪花', emoji: '🌨️', rarity: 'C', type: 'normal' },
      { id: 's4', name: '冰城堡', emoji: '🏰', rarity: 'D', type: 'normal' },
      { id: 's5', name: '冰鞋', emoji: '⛸️', rarity: 'E', type: 'normal' },
      { id: 's6', name: '馴鹿', emoji: '🦌', rarity: 'F', type: 'normal' },
      { id: 's7', name: '雪人', emoji: '⛄', rarity: 'G', type: 'normal' },
      { id: 's8', name: '冰心', emoji: '💙', rarity: 'H', type: 'normal' },
      { id: 's9', name: '北極光', emoji: '🌌', rarity: 'I', type: 'normal' },
      { id: 'wild', name: 'WILD', emoji: '❆', label: 'WILD', rarity: 'WILD', type: 'wild' },
      { id: 'scatter', name: 'SCATTER', emoji: '✧', label: 'SCATTER', rarity: 'SCATTER', type: 'scatter' },
      { id: 'bonus', name: 'BONUS', emoji: '🎄', label: 'BONUS', rarity: 'BONUS', type: 'bonus' },
    ],
  },
  // 机台08：古埃及寶藏
  {
    id: 'slot-08',
    number: 8,
    name: '古埃及寶藏',
    background: 'linear-gradient(135deg, #8b4513 0%, #d2b48c 100%)',
    primaryColor: '#d2b48c',
    secondaryColor: '#8b4513',
    accentColor: '#ffd700',
    symbols: [
      { id: 's1', name: '金字塔', emoji: '🔺', rarity: 'A', type: 'normal' },
      { id: 's2', name: '法老', emoji: '👤', rarity: 'B', type: 'normal' },
      { id: 's3', name: '聖甲蟲', emoji: '🐞', rarity: 'C', type: 'normal' },
      { id: 's4', name: '眼睛', emoji: '👁️', rarity: 'D', type: 'normal' },
      { id: 's5', name: '金杯', emoji: '🏺', rarity: 'E', type: 'normal' },
      { id: 's6', name: '捲軸', emoji: '📜', rarity: 'F', type: 'normal' },
      { id: 's7', name: '聖鷹', emoji: '🦅', rarity: 'G', type: 'normal' },
      { id: 's8', name: '棕褐心', emoji: '🟤', rarity: 'H', type: 'normal' },
      { id: 's9', name: '法杖', emoji: '🏑', rarity: 'I', type: 'normal' },
      { id: 'wild', name: 'WILD', emoji: '🔑', label: 'WILD', rarity: 'WILD', type: 'wild' },
      { id: 'scatter', name: 'SCATTER', emoji: '✨', label: 'SCATTER', rarity: 'SCATTER', type: 'scatter' },
      { id: 'bonus', name: 'BONUS', emoji: '💰', label: 'BONUS', rarity: 'BONUS', type: 'bonus' },
    ],
  },
  // 机台09：傳說寶劍
  {
    id: 'slot-09',
    number: 9,
    name: '傳說寶劍',
    background: 'linear-gradient(135deg, #4b0082 0%, #9932cc 100%)',
    primaryColor: '#9932cc',
    secondaryColor: '#4b0082',
    accentColor: '#dda0dd',
    symbols: [
      { id: 's1', name: '寶劍', emoji: '⚔️', rarity: 'A', type: 'normal' },
      { id: 's2', name: '盔甲', emoji: '🛡️', rarity: 'B', type: 'normal' },
      { id: 's3', name: '皇冠', emoji: '👑', rarity: 'C', type: 'normal' },
      { id: 's4', name: '聖杯', emoji: '🍷', rarity: 'D', type: 'normal' },
      { id: 's5', name: '龍', emoji: '🐲', rarity: 'E', type: 'normal' },
      { id: 's6', name: '騎士', emoji: '🧔', rarity: 'F', type: 'normal' },
      { id: 's7', name: '魔法石', emoji: '🔮', rarity: 'G', type: 'normal' },
      { id: 's8', name: '紫心', emoji: '💜', rarity: 'H', type: 'normal' },
      { id: 's9', name: '紋章', emoji: '🎖️', rarity: 'I', type: 'normal' },
      { id: 'wild', name: 'WILD', emoji: '✨', label: 'WILD', rarity: 'WILD', type: 'wild' },
      { id: 'scatter', name: 'SCATTER', emoji: '⭐', label: 'SCATTER', rarity: 'SCATTER', type: 'scatter' },
      { id: 'bonus', name: 'BONUS', emoji: '🏆', label: 'BONUS', rarity: 'BONUS', type: 'bonus' },
    ],
  },
  // 机台10：魔法師塔
  {
    id: 'slot-10',
    number: 10,
    name: '魔法師塔',
    background: 'linear-gradient(135deg, #2c3e50 0%, #34495e 100%)',
    primaryColor: '#34495e',
    secondaryColor: '#2c3e50',
    accentColor: '#3498db',
    symbols: [
      { id: 's1', name: '魔法師', emoji: '🧙', rarity: 'A', type: 'normal' },
      { id: 's2', name: '魔杖', emoji: '🪄', rarity: 'B', type: 'normal' },
      { id: 's3', name: '水晶球', emoji: '🔮', rarity: 'C', type: 'normal' },
      { id: 's4', name: '古書', emoji: '📖', rarity: 'D', type: 'normal' },
      { id: 's5', name: '魔法陣', emoji: '⭐', rarity: 'E', type: 'normal' },
      { id: 's6', name: '貓頭鷹', emoji: '🦉', rarity: 'F', type: 'normal' },
      { id: 's7', name: '蠟燭', emoji: '🕯️', rarity: 'G', type: 'normal' },
      { id: 's8', name: '藍心', emoji: '💙', rarity: 'H', type: 'normal' },
      { id: 's9', name: '塔', emoji: '🏯', rarity: 'I', type: 'normal' },
      { id: 'wild', name: 'WILD', emoji: '✨', label: 'WILD', rarity: 'WILD', type: 'wild' },
      { id: 'scatter', name: 'SCATTER', emoji: '🌟', label: 'SCATTER', rarity: 'SCATTER', type: 'scatter' },
      { id: 'bonus', name: 'BONUS', emoji: '🎁', label: 'BONUS', rarity: 'BONUS', type: 'bonus' },
    ],
  },
  // 机台11：牛仔西部
  {
    id: 'slot-11',
    number: 11,
    name: '牛仔西部',
    background: 'linear-gradient(135deg, #8b4513 0%, #d2691e 100%)',
    primaryColor: '#d2691e',
    secondaryColor: '#8b4513',
    accentColor: '#daa520',
    symbols: [
      { id: 's1', name: '牛仔', emoji: '🤠', rarity: 'A', type: 'normal' },
      { id: 's2', name: '馬', emoji: '🐴', rarity: 'B', type: 'normal' },
      { id: 's3', name: '槍', emoji: '🔫', rarity: 'C', type: 'normal' },
      { id: 's4', name: '沙龍', emoji: '🏚️', rarity: 'D', type: 'normal' },
      { id: 's5', name: '金幣', emoji: '🪙', rarity: 'E', type: 'normal' },
      { id: 's6', name: '帳篷', emoji: '⛺', rarity: 'F', type: 'normal' },
      { id: 's7', name: '靴子', emoji: '👢', rarity: 'G', type: 'normal' },
      { id: 's8', name: '褐心', emoji: '🟤', rarity: 'H', type: 'normal' },
      { id: 's9', name: '日落', emoji: '🌅', rarity: 'I', type: 'normal' },
      { id: 'wild', name: 'WILD', emoji: '🌵', label: 'WILD', rarity: 'WILD', type: 'wild' },
      { id: 'scatter', name: 'SCATTER', emoji: '⭐', label: 'SCATTER', rarity: 'SCATTER', type: 'scatter' },
      { id: 'bonus', name: 'BONUS', emoji: '🎯', label: 'BONUS', rarity: 'BONUS', type: 'bonus' },
    ],
  },
  // 机台12：花園蝴蝶
  {
    id: 'slot-12',
    number: 12,
    name: '花園蝴蝶',
    background: 'linear-gradient(135deg, #ff1493 0%, #ff69b4 100%)',
    primaryColor: '#ff69b4',
    secondaryColor: '#ff1493',
    accentColor: '#ffc0cb',
    symbols: [
      { id: 's1', name: '蝴蝶', emoji: '🦋', rarity: 'A', type: 'normal' },
      { id: 's2', name: '玫瑰', emoji: '🌹', rarity: 'B', type: 'normal' },
      { id: 's3', name: '牡丹', emoji: '🌸', rarity: 'C', type: 'normal' },
      { id: 's4', name: '向日葵', emoji: '🌻', rarity: 'D', type: 'normal' },
      { id: 's5', name: '蜜蜂', emoji: '🐝', rarity: 'E', type: 'normal' },
      { id: 's6', name: '瓢蟲', emoji: '🐞', rarity: 'F', type: 'normal' },
      { id: 's7', name: '蛙', emoji: '🐸', rarity: 'G', type: 'normal' },
      { id: 's8', name: '粉心', emoji: '💕', rarity: 'H', type: 'normal' },
      { id: 's9', name: '彩虹', emoji: '🌈', rarity: 'I', type: 'normal' },
      { id: 'wild', name: 'WILD', emoji: '🌺', label: 'WILD', rarity: 'WILD', type: 'wild' },
      { id: 'scatter', name: 'SCATTER', emoji: '✿', label: 'SCATTER', rarity: 'SCATTER', type: 'scatter' },
      { id: 'bonus', name: 'BONUS', emoji: '🎀', label: 'BONUS', rarity: 'BONUS', type: 'bonus' },
    ],
  },
  // 机台13：機械朋克
  {
    id: 'slot-13',
    number: 13,
    name: '機械朋克',
    background: 'linear-gradient(135deg, #2c3e50 0%, #34495e 100%)',
    primaryColor: '#34495e',
    secondaryColor: '#2c3e50',
    accentColor: '#e67e22',
    symbols: [
      { id: 's1', name: '機器人', emoji: '🤖', rarity: 'A', type: 'normal' },
      { id: 's2', name: '齒輪', emoji: '⚙️', rarity: 'B', type: 'normal' },
      { id: 's3', name: '電路板', emoji: '🔌', rarity: 'C', type: 'normal' },
      { id: 's4', name: '燈泡', emoji: '💡', rarity: 'D', type: 'normal' },
      { id: 's5', name: '扳手', emoji: '🔧', rarity: 'E', type: 'normal' },
      { id: 's6', name: '錘子', emoji: '🔨', rarity: 'F', type: 'normal' },
      { id: 's7', name: '電線', emoji: '🔋', rarity: 'G', type: 'normal' },
      { id: 's8', name: '橙心', emoji: '🧡', rarity: 'H', type: 'normal' },
      { id: 's9', name: '火焰', emoji: '🔥', rarity: 'I', type: 'normal' },
      { id: 'wild', name: 'WILD', emoji: '⚡', label: 'WILD', rarity: 'WILD', type: 'wild' },
      { id: 'scatter', name: 'SCATTER', emoji: '✨', label: 'SCATTER', rarity: 'SCATTER', type: 'scatter' },
      { id: 'bonus', name: 'BONUS', emoji: '🎯', label: 'BONUS', rarity: 'BONUS', type: 'bonus' },
    ],
  },
  // 机台14：幽靈鬼屋
  {
    id: 'slot-14',
    number: 14,
    name: '幽靈鬼屋',
    background: 'linear-gradient(135deg, #1a1a2e 0%, #16213e 100%)',
    primaryColor: '#16213e',
    secondaryColor: '#1a1a2e',
    accentColor: '#0f3460',
    symbols: [
      { id: 's1', name: '幽靈', emoji: '👻', rarity: 'A', type: 'normal' },
      { id: 's2', name: '蜘蛛', emoji: '🕷️', rarity: 'B', type: 'normal' },
      { id: 's3', name: '蜘蛛網', emoji: '🕸️', rarity: 'C', type: 'normal' },
      { id: 's4', name: '骨頭', emoji: '💀', rarity: 'D', type: 'normal' },
      { id: 's5', name: '棺材', emoji: '⚰️', rarity: 'E', type: 'normal' },
      { id: 's6', name: '蝙蝠', emoji: '🦇', rarity: 'F', type: 'normal' },
      { id: 's7', name: '燭火', emoji: '🕯️', rarity: 'G', type: 'normal' },
      { id: 's8', name: '黑心', emoji: '🖤', rarity: 'H', type: 'normal' },
      { id: 's9', name: '月亮', emoji: '🌙', rarity: 'I', type: 'normal' },
      { id: 'wild', name: 'WILD', emoji: '👿', label: 'WILD', rarity: 'WILD', type: 'wild' },
      { id: 'scatter', name: 'SCATTER', emoji: '👁️', label: 'SCATTER', rarity: 'SCATTER', type: 'scatter' },
      { id: 'bonus', name: 'BONUS', emoji: '🎃', label: 'BONUS', rarity: 'BONUS', type: 'bonus' },
    ],
  },
  // 机台15：櫻花戀舞
  {
    id: 'slot-15',
    number: 15,
    name: '櫻花戀舞',
    background: 'linear-gradient(135deg, #ff69b4 0%, #ffb6c1 100%)',
    primaryColor: '#ffb6c1',
    secondaryColor: '#ff69b4',
    accentColor: '#ffc0cb',
    symbols: [
      { id: 's1', name: '櫻花', emoji: '🌸', rarity: 'A', type: 'normal' },
      { id: 's2', name: '舞女', emoji: '💃', rarity: 'B', type: 'normal' },
      { id: 's3', name: '摺紙鶴', emoji: '🪶', rarity: 'C', type: 'normal' },
      { id: 's4', name: '燈籠', emoji: '🏮', rarity: 'D', type: 'normal' },
      { id: 's5', name: '竹子', emoji: '🎋', rarity: 'E', type: 'normal' },
      { id: 's6', name: '福袋', emoji: '🎎', rarity: 'F', type: 'normal' },
      { id: 's7', name: '和風團扇', emoji: '👘', rarity: 'G', type: 'normal' },
      { id: 's8', name: '粉心', emoji: '💗', rarity: 'H', type: 'normal' },
      { id: 's9', name: '日本家紋', emoji: '🎴', rarity: 'I', type: 'normal' },
      { id: 'wild', name: 'WILD', emoji: '⛩️', label: 'WILD', rarity: 'WILD', type: 'wild' },
      { id: 'scatter', name: 'SCATTER', emoji: '✨', label: 'SCATTER', rarity: 'SCATTER', type: 'scatter' },
      { id: 'bonus', name: 'BONUS', emoji: '🎀', label: 'BONUS', rarity: 'BONUS', type: 'bonus' },
    ],
  },
 // 机台16：非洲狂野
  {
    id: 'slot-16',
    number: 16,
    name: '非洲狂野',
    background: 'linear-gradient(135deg, #8b6914 0%, #cd853f 100%)',
    primaryColor: '#cd853f',
    secondaryColor: '#8b6914',
    accentColor: '#daa520',
    symbols: [
      { id: 's1', name: '獅子', emoji: '🦁', rarity: 'A', type: 'normal' },
      { id: 's2', name: '長頸鹿', emoji: '🦒', rarity: 'B', type: 'normal' },
      { id: 's3', name: '斑馬', emoji: '🦓', rarity: 'C', type: 'normal' },
      { id: 's4', name: '大象', emoji: '🐘', rarity: 'D', type: 'normal' },
      { id: 's5', name: '犀牛', emoji: '🦏', rarity: 'E', type: 'normal' },
      { id: 's6', name: '狒狒', emoji: '🐵', rarity: 'F', type: 'normal' },
      { id: 's7', name: '羚羊', emoji: '🦌', rarity: 'G', type: 'normal' },
      { id: 's8', name: '褐心', emoji: '🟤', rarity: 'H', type: 'normal' },
      { id: 's9', name: '日落', emoji: '🌅', rarity: 'I', type: 'normal' },
      { id: 'wild', name: 'WILD', emoji: '🌍', label: 'WILD', rarity: 'WILD', type: 'wild' },
      { id: 'scatter', name: 'SCATTER', emoji: '🌴', label: 'SCATTER', rarity: 'SCATTER', type: 'scatter' },
      { id: 'bonus', name: 'BONUS', emoji: '🎯', label: 'BONUS', rarity: 'BONUS', type: 'bonus' },
    ],
  },
  // 机台17：聖誕奇蹟
  {
    id: 'slot-17',
    number: 17,
    name: '聖誕奇蹟',
    background: 'linear-gradient(135deg, #c41e3a 0%, #165b33 100%)',
    primaryColor: '#165b33',
    secondaryColor: '#c41e3a',
    accentColor: '#ffd700',
    symbols: [
      { id: 's1', name: '聖誕老人', emoji: '🎅', rarity: 'A', type: 'normal' },
      { id: 's2', name: '聖誕樹', emoji: '🎄', rarity: 'B', type: 'normal' },
      { id: 's3', name: '禮物盒', emoji: '🎁', rarity: 'C', type: 'normal' },
      { id: 's4', name: '鈴鐺', emoji: '🔔', rarity: 'D', type: 'normal' },
      { id: 's5', name: '雪橇', emoji: '🛷', rarity: 'E', type: 'normal' },
      { id: 's6', name: '馴鹿', emoji: '🦌', rarity: 'F', type: 'normal' },
      { id: 's7', name: '襪子', emoji: '🧦', rarity: 'G', type: 'normal' },
      { id: 's8', name: '紅心', emoji: '❤️', rarity: 'H', type: 'normal' },
      { id: 's9', name: '雪人', emoji: '⛄', rarity: 'I', type: 'normal' },
      { id: 'wild', name: 'WILD', emoji: '⭐', label: 'WILD', rarity: 'WILD', type: 'wild' },
      { id: 'scatter', name: 'SCATTER', emoji: '❄️', label: 'SCATTER', rarity: 'SCATTER', type: 'scatter' },
      { id: 'bonus', name: 'BONUS', emoji: '🎊', label: 'BONUS', rarity: 'BONUS', type: 'bonus' },
    ],
  },
  // 机台18：山寨飛俠
  {
    id: 'slot-18',
    number: 18,
    name: '山寨飛俠',
    background: 'linear-gradient(135deg, #2c3e50 0%, #8b4513 100%)',
    primaryColor: '#8b4513',
    secondaryColor: '#2c3e50',
    accentColor: '#d2b48c',
    symbols: [
      { id: 's1', name: '劍俠', emoji: '🗡️', rarity: 'A', type: 'normal' },
      { id: 's2', name: '山峰', emoji: '⛰️', rarity: 'B', type: 'normal' },
      { id: 's3', name: '龍', emoji: '🐉', rarity: 'C', type: 'normal' },
      { id: 's4', name: '廟宇', emoji: '⛩️', rarity: 'D', type: 'normal' },
      { id: 's5', name: '尖塔', emoji: '🏯', rarity: 'E', type: 'normal' },
      { id: 's6', name: '大鐘', emoji: '🔔', rarity: 'F', type: 'normal' },
      { id: 's7', name: '月亮', emoji: '🌙', rarity: 'G', type: 'normal' },
      { id: 's8', name: '褐心', emoji: '🟤', rarity: 'H', type: 'normal' },
      { id: 's9', name: '星星', emoji: '⭐', rarity: 'I', type: 'normal' },
      { id: 'wild', name: 'WILD', emoji: '☯️', label: 'WILD', rarity: 'WILD', type: 'wild' },
      { id: 'scatter', name: 'SCATTER', emoji: '✨', label: 'SCATTER', rarity: 'SCATTER', type: 'scatter' },
      { id: 'bonus', name: 'BONUS', emoji: '🎯', label: 'BONUS', rarity: 'BONUS', type: 'bonus' },
    ],
  },
  // 机台19：深海怪獸
  {
    id: 'slot-19',
    number: 19,
    name: '深海怪獸',
    background: 'linear-gradient(135deg, #000080 0%, #1a1a3e 100%)',
    primaryColor: '#1a1a3e',
    secondaryColor: '#000080',
    accentColor: '#00d9ff',
    symbols: [
      { id: 's1', name: '章魚', emoji: '🐙', rarity: 'A', type: 'normal' },
      { id: 's2', name: '烏賊', emoji: '🦑', rarity: 'B', type: 'normal' },
      { id: 's3', name: '海怪', emoji: '🐉', rarity: 'C', type: 'normal' },
      { id: 's4', name: '海蛇', emoji: '🐍', rarity: 'D', type: 'normal' },
      { id: 's5', name: '海螺', emoji: '🐚', rarity: 'E', type: 'normal' },
      { id: 's6', name: '磷蝦', emoji: '🦐', rarity: 'F', type: 'normal' },
      { id: 's7', name: '潛艇', emoji: '⛵', rarity: 'G', type: 'normal' },
      { id: 's8', name: '青心', emoji: '💙', rarity: 'H', type: 'normal' },
      { id: 's9', name: '漩渦', emoji: '🌀', rarity: 'I', type: 'normal' },
      { id: 'wild', name: 'WILD', emoji: '⚓', label: 'WILD', rarity: 'WILD', type: 'wild' },
      { id: 'scatter', name: 'SCATTER', emoji: '💎', label: 'SCATTER', rarity: 'SCATTER', type: 'scatter' },
      { id: 'bonus', name: 'BONUS', emoji: '🎁', label: 'BONUS', rarity: 'BONUS', type: 'bonus' },
    ],
  },
  // 机台20：星際帝國
  {
    id: 'slot-20',
    number: 20,
    name: '星際帝國',
    background: 'linear-gradient(135deg, #0a0019 0%, #22005d 100%)',
    primaryColor: '#22005d',
    secondaryColor: '#0a0019',
    accentColor: '#ff00ff',
    symbols: [
      { id: 's1', name: '帝皇', emoji: '👑', rarity: 'A', type: 'normal' },
      { id: 's2', name: '戰艦', emoji: '🚀', rarity: 'B', type: 'normal' },
      { id: 's3', name: '外星人', emoji: '👽', rarity: 'C', type: 'normal' },
      { id: 's4', name: '光劍', emoji: '⚡', rarity: 'D', type: 'normal' },
      { id: 's5', name: '行星', emoji: '🪐', rarity: 'E', type: 'normal' },
      { id: 's6', name: '隕石', emoji: '☄️', rarity: 'F', type: 'normal' },
      { id: 's7', name: '黑洞', emoji: '⚫', rarity: 'G', type: 'normal' },
      { id: 's8', name: '紫心', emoji: '💜', rarity: 'H', type: 'normal' },
      { id: 's9', name: '星團', emoji: '✨', rarity: 'I', type: 'normal' },
      { id: 'wild', name: 'WILD', emoji: '🌌', label: 'WILD', rarity: 'WILD', type: 'wild' },
      { id: 'scatter', name: 'SCATTER', emoji: '💫', label: 'SCATTER', rarity: 'SCATTER', type: 'scatter' },
      { id: 'bonus', name: 'BONUS', emoji: '🏆', label: 'BONUS', rarity: 'BONUS', type: 'bonus' },
    ],
  },
]

export function getSlotMachineThemeByNumber(number: number): SlotMachineTheme | undefined {
  return SLOT_MACHINE_THEMES.find(theme => theme.number === number)
}

export function getAllSlotMachineThemes(): SlotMachineTheme[] {
  return SLOT_MACHINE_THEMES
} 
